### ISSUE TITLE
German language model does not return german special characters "äöüß"

### ISSUE THREAD

**Issue by Justus-Jonas** [PaddlePaddle/PaddleOCR#1646]
Dear all, 

I tried the german language model today. On every image I tried, it was not recognizing the letters 'ÄÖÜäöüß' and was just skipping them.

My very simple code: 

`from paddleocr import PaddleOCR,draw_ocr`

`ocr = PaddleOCR(use_angle_cls=True, lang='german')`

`result = ocr.ocr(filepath, cls=True)`

`strings = []`

`for line in result:`
`strings.append(line[1][0])`

`print(strings)`

All strings just skip these letters, so the word `Grüßen` would be returned as `Gren`. Did I mess something up with the model configuration or is this a bug? 

If you need images for testing, feel free to hit me up.

Thanks in advance! 

Best, 

Justus

**Comment by tink2123** [comment]
Dear Justus,

Thanks for your use. The reason why these characters are not recognized is that they are not included in the list of [german_dict.txt](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/ppocr/utils/dict/german_dict.txt) we support.


Sorry for the inconvenience. Since we don't know enough about German, there were omissions when setting up the dictionary. 

**Would you like to help us polish the dictionary file?** You can create a pull request to update the [old dictionary](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/ppocr/utils/dict/german_dict.txt). Or attach the dictionary file to this issue.

We will update the model as soon as possible and thank you on the homepage.

Best,

Xiaoting

**Comment by Justus-Jonas** [comment]
Dear Xiaoting, 

thanks a lot for your reply. I fixed it and created a pull request [add german special characters #1659](https://github.com/PaddlePaddle/PaddleOCR/pull/1659).

If you have any German specific questions in the future, feel free to reach out to me. I am always happy to help.

Best, 

Justus

**Comment by grasswolfs** [comment]
Dear Justus,

We have updated the German recognition model recently. Welcome to have a try in following docs
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_en/multi_languages_en.md

B. R
Daniel

**Comment by Evezerest** [comment]
The issue will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up. It is recommended to pull and try the latest code first.
该问题将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。

**Comment by SDK1410** [comment]
Dear all,

I noticed your comments regarding the special German characters äöü and the supposed fix for this 'bug.' I attempted to test the updated version, but unfortunately, it did not work as expected for me. I have upgraded PaddleOCR to the latest version, 2.7.0.3, and specified the language as German. However, instead of correctly recognizing 'Ö,' I am receiving 'O' in the output. It's possible that I might be using the wrong model or there is some other issue. Could you please assist me with this?

Thank you.

**Comment by jonaumann** [comment]
I have the same problem as SDK1410, german letters like Ö are not recognized, so it seems the fix did not work?

**Comment by neilyoung** [comment]
Doesn't work for German Umlauts, that's it

**Comment by jlplenio** [comment]
Any updates here?

**Comment by sayinmehmet47** [comment]
@Justus-Jonas did you find a workaround for it ? i also scan some insurance cards and i saw the german characters did not detected.
