### ISSUE TITLE
鲲鹏920 Arm64 使用 OCR V5解析pdf或者图片报错：`Segmentation fault` is detected by the operating system

### ISSUE THREAD

**Issue by sduqlsc** [PaddlePaddle/PaddleOCR#16609]
### 🔎 Search before asking

- [x] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [x] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [x] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

图片大小为1656*2339，无论enable_mkldnn是True还是False，都会报错。pdf识别同样的错误，145K以及3.8M都会报错，但是使用general_ocr_002.png正常。同样的文件，V3目前表现正常。

```bash
ocr = PaddleOCR(
            lang="ch",
            ocr_version="PP-OCRv3",
            enable_mkldnn=True,
            cpu_threads=8,
            use_doc_orientation_classify=False,
            use_doc_unwarping=False,
            use_textline_orientation=False,
            device='cpu'
        )
```

### 🏃‍♂️ Environment (运行环境)

```bash
OS : Ubuntu 22.04.4  ARM64 Docker
Python: 3.10.12
paddleocr                3.2.0
CPU: kunpeng-920
CUDA： None
NPU： None
```

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

```bash
Python 3.10.12 (main, Aug 15 2025, 14:32:43) [GCC 11.4.0] on linux

>>> import os
>>> import sys
>>> import time
>>> import io
>>> import json
>>> from datetime import datetime
>>> from paddleocr import PaddleOCR
>>> img_file="../img_test/contract_00.jpg"
>>> ocr = PaddleOCR(
...             lang="ch",
...             device='cpu',
...             enable_mkldnn=False,
...             cpu_threads=8,
...             use_doc_orientation_classify=False,
...             use_doc_unwarping=False,
...             use_textline_orientation=True
...         )
Creating model: ('PP-LCNet_x1_0_textline_ori', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-LCNet_x1_0_textline_ori`.
Creating model: ('PP-OCRv5_server_det', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-OCRv5_server_det`.
Creating model: ('PP-OCRv5_server_rec', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/root/.paddlex/official_models/PP-OCRv5_server_rec`.
>>> result = ocr.predict(img_file)


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun(bool)
1   paddle::framework::NaiveExecutor::RunInterpreterCore(std::vector<std::string, std::allocator<std::string > > const&, bool, bool)
2   paddle::framework::InterpreterCore::Run(std::vector<std::string, std::allocator<std::string > > const&, bool, bool, bool, bool)
3   paddle::framework::PirInterpreter::Run(std::vector<std::string, std::allocator<std::string > > const&, bool, bool, bool, bool)
4   paddle::framework::PirInterpreter::TraceRunImpl()
5   paddle::framework::PirInterpreter::TraceRunInstructionList(std::vector<std::unique_ptr<paddle::framework::InstructionBase, std::default_delete<paddle::framework::InstructionBase> >, std::allocator<std::unique_ptr<paddle::framework::InstructionBase, std::default_delete<paddle::framework::InstructionBase> > > > const&)
6   paddle::framework::PirInterpreter::RunInstructionBase(paddle::framework::InstructionBase*)
7   paddle::framework::PhiKernelInstruction::Run()
8   phi::KernelImpl<void (*)(phi::CPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::string const&, std::vector<int, std::allocator<int> > const&, int, std::string const&, phi::DenseTensor*), &(void phi::ConvKernel<float, phi::CPUContext>(phi::CPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::string const&, std::vector<int, std::allocator<int> > const&, int, std::string const&, phi::DenseTensor*))>::Compute(phi::KernelContext*)
9   void phi::ConvKernelImpl<float, phi::CPUContext>(phi::CPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::string const&, int, std::vector<int, std::allocator<int> > const&, std::string const&, phi::DenseTensor*)
10  phi::funcs::Im2ColFunctor<(phi::funcs::ColFormat)0, phi::CPUContext, float>::operator()(phi::CPUContext const&, phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, phi::DenseTensor*, common::DataLayout)

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1759193212 (unix time) try "date -d @1759193212" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0xfff58b4b1480) received by PID 171857 (TID 0xfffe1c250420) from PID 18446744071751537792 ***]

Segmentation fault (core dumped)

```

**Comment by pulkitchowdry** [comment]
I have observed a similar issue on macOS. Following is the error message,

Creating model: ('PP-OCRv5_server_det', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/Users/cc/.paddlex/official_models/PP-OCRv5_server_det`.
Creating model: ('PP-OCRv5_server_rec', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/Users/cc/.paddlex/official_models/PP-OCRv5_server_rec`.
zsh: segmentation fault  python3 preprocessing/image_proc.py

I observe this whenever my input is a png or pdf file while it never happens for jpg files. I am not sure if this is due to multi-processing. In v5, using cpu_thread=1 also did not solve it.

OCR Model
ocr = PaddleOCR(
    text_detection_model_name="PP-OCRv5_server_det",
    text_recognition_model_name="PP-OCRv5_server_rec",
    use_doc_orientation_classify=False,
    use_doc_unwarping=False,
    use_textline_orientation=False,
)

Environment
PaddleOCR Version: 3.2.0
Python Version: 3.11.4
OS: macOS Sequoia Version 15.6.1

**Comment by cuicheng01** [comment]
Hello, this issue may be caused by a boundary condition bug in the Paddle framework, which has already been fixed in this [PR](https://github.com/PaddlePaddle/Paddle/pull/75261). If you use the develop version of paddlepaddle, this problem should no longer occur.

**Comment by pulkitchowdry** [comment]
Thanks for sharing some insights. I tried using the develop version - paddlepaddle-3.3.0.dev20250930-cp311-cp311-macosx_11_0_arm64.whl

But the issue persists.

`
Error
zsh: segmentation fault  python3 ./preprocessing/image_proc.py
Additional multi-processing warning after this,
UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

paddleocr version: 3.2.0
paddlepaddle version: 3.3.0.dev20250930
paddlex version: 3.2.1
Python version: 3.11.4
`

**Comment by sduqlsc** [comment]
> Hello, this issue may be caused by a boundary condition bug in the Paddle framework, which has already been fixed in this [PR](https://github.com/PaddlePaddle/Paddle/pull/75261). If you use the develop version of paddlepaddle, this problem should no longer occur.

is the same solution on arm64 linux, coz i tried on dev branch, seems no luck? @cuicheng01

**Comment by scyyh11** [comment]
> Thanks for sharing some insights. I tried using the develop version - paddlepaddle-3.3.0.dev20250930-cp311-cp311-macosx_11_0_arm64.whl
> 
> But the issue persists.
> 
> ` Error zsh: segmentation fault python3 ./preprocessing/image_proc.py Additional multi-processing warning after this, UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown warnings.warn('resource_tracker: There appear to be %d '
> 
> paddleocr version: 3.2.0 paddlepaddle version: 3.3.0.dev20250930 paddlex version: 3.2.1 Python version: 3.11.4 `

Can you send me the test image that you used so that I can try to reproduce the error?

**Comment by scyyh11** [comment]
> Hello, this issue may be caused by a boundary condition bug in the Paddle framework, which has already been fixed in this [PR](https://github.com/PaddlePaddle/Paddle/pull/75261). If you use the develop version of paddlepaddle, this problem should no longer occur.

I have investigate into this issue, my fix in previous PR was focus on `im2col_common` . Current bug might come from `im2col_sh1sw1dh1dw1ph1pw1`. I just created a draft PR [#75716](https://github.com/PaddlePaddle/Paddle/pull/75716) to fix it.
我在那个PR里修复的是 `im2col_common` 函数里相关的问题，这个bug可能是因为 `im2col_sh1sw1dh1dw1ph1pw1` 函数部分没有进行修复，当时排查时候没有注意到相关的问题。我刚提了draft PR [#75716](https://github.com/PaddlePaddle/Paddle/pull/75716)来修复新的问题。

**Comment by scyyh11** [comment]
> Thanks for sharing some insights. I tried using the develop version - paddlepaddle-3.3.0.dev20250930-cp311-cp311-macosx_11_0_arm64.whl
> 
> But the issue persists.
> 
> ` Error zsh: segmentation fault python3 ./preprocessing/image_proc.py Additional multi-processing warning after this, UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown warnings.warn('resource_tracker: There appear to be %d '
> 
> paddleocr version: 3.2.0 paddlepaddle version: 3.3.0.dev20250930 paddlex version: 3.2.1 Python version: 3.11.4 `

Hi, can you share the test image you used?

**Comment by sduqlsc** [comment]
> > Thanks for sharing some insights. I tried using the develop version - paddlepaddle-3.3.0.dev20250930-cp311-cp311-macosx_11_0_arm64.whl
> > But the issue persists.
> > ` Error zsh: segmentation fault python3 ./preprocessing/image_proc.py Additional multi-processing warning after this, UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown warnings.warn('resource_tracker: There appear to be %d '
> > paddleocr version: 3.2.0 paddlepaddle version: 3.3.0.dev20250930 paddlex version: 3.2.1 Python version: 3.11.4 `
> 
> Hi, can you share the test image you used?

me or    @pulkitchowdry ?

**Comment by scyyh11** [comment]
> > > Thanks for sharing some insights. I tried using the develop version - paddlepaddle-3.3.0.dev20250930-cp311-cp311-macosx_11_0_arm64.whl
> > > But the issue persists.
> > > `Error zsh: segmentation fault python3 ./preprocessing/image_proc.py Additional multi-processing warning after this, UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown warnings.warn('resource_tracker: There appear to be %d ' paddleocr version: 3.2.0 paddlepaddle version: 3.3.0.dev20250930 paddlex version: 3.2.1 Python version: 3.11.4`
> > 
> > 
> > Hi, can you share the test image you used?
> 
> me or [@pulkitchowdry](https://github.com/pulkitchowdry) ?

My device is macOS, so your source would be great. Thank you.

**Comment by pulkitchowdry** [comment]
@scyyh11 Thanks for reaching out. On further analysis, I observe the below,

1. When I take a screenshot on MacOS or if I extract images from PDF using library like pdf2image (Attached is sample image) then it Seg Faults.

2. When I extract images from same PDF file but using library like fitz (PyMuPDF) then it works properly.

Thanks
(Updated comment to only have not working image to avoid confusion.)

<img width="1654" height="2339" alt="Image" src="https://github.com/user-attachments/assets/a6a50706-f8b5-4f44-9a2a-e5a04d5b2d0d" />

**Comment by scyyh11** [comment]
> 1. library like pdf2image

Sorry about the confusion, the problem does occur in the newest nightly build. I compiled from the previous fixed PR version and it worked fine. I will look into what causes the issue again. Thank you for the quick response. The temporary fix is to resize the image to less than 1200 pixels on both edge.

**Comment by scyyh11** [comment]
Just created a new PR https://github.com/PaddlePaddle/Paddle/pull/75731, my local test works fine now, hopefully this will fix the issue.

**Comment by pulkitchowdry** [comment]
> Just created a new PR https://github.com/PaddlePaddle/Paddle/pull/75731, my local test works fine now, hopefully this will fix the issue.

Thanks for identifying the issue.

**Comment by sduqlsc** [comment]
@scyyh11 是否还需要提供鲲鹏上的信息？

> > > > Thanks for sharing some insights. I tried using the develop version - paddlepaddle-3.3.0.dev20250930-cp311-cp311-macosx_11_0_arm64.whl
> > > > But the issue persists.
> > > > `Error zsh: segmentation fault python3 ./preprocessing/image_proc.py Additional multi-processing warning after this, UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown warnings.warn('resource_tracker: There appear to be %d ' paddleocr version: 3.2.0 paddlepaddle version: 3.3.0.dev20250930 paddlex version: 3.2.1 Python version: 3.11.4`
> > > 
> > > 
> > > Hi, can you share the test image you used?
> > 
> > 
> > me or [@pulkitchowdry](https://github.com/pulkitchowdry) ?
> 
> My device is macOS, so your source would be great. Thank you.

**Comment by scyyh11** [comment]
> [@scyyh11](https://github.com/scyyh11) 是否还需要提供鲲鹏上的信息？
> 
> > > > > Thanks for sharing some insights. I tried using the develop version - paddlepaddle-3.3.0.dev20250930-cp311-cp311-macosx_11_0_arm64.whl
> > > > > But the issue persists.
> > > > > `Error zsh: segmentation fault python3 ./preprocessing/image_proc.py Additional multi-processing warning after this, UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown warnings.warn('resource_tracker: There appear to be %d ' paddleocr version: 3.2.0 paddlepaddle version: 3.3.0.dev20250930 paddlex version: 3.2.1 Python version: 3.11.4`
> > > > 
> > > > 
> > > > Hi, can you share the test image you used?
> > > 
> > > 
> > > me or [@pulkitchowdry](https://github.com/pulkitchowdry) ?
> > 
> > 
> > My device is macOS, so your source would be great. Thank you.

我前两天的PR尝试修复了在macOS上的问题，您可以尝试用nightly build的whl再跑一次。

**Comment by sduqlsc** [comment]
> > [@scyyh11](https://github.com/scyyh11) 是否还需要提供鲲鹏上的信息？
> > > > > > Thanks for sharing some insights. I tried using the develop version - paddlepaddle-3.3.0.dev20250930-cp311-cp311-macosx_11_0_arm64.whl
> > > > > > But the issue persists.
> > > > > > `Error zsh: segmentation fault python3 ./preprocessing/image_proc.py Additional multi-processing warning after this, UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown warnings.warn('resource_tracker: There appear to be %d ' paddleocr version: 3.2.0 paddlepaddle version: 3.3.0.dev20250930 paddlex version: 3.2.1 Python version: 3.11.4`
> > > > > 
> > > > > 
> > > > > Hi, can you share the test image you used?
> > > > 
> > > > 
> > > > me or [@pulkitchowdry](https://github.com/pulkitchowdry) ?
> > > 
> > > 
> > > My device is macOS, so your source would be great. Thank you.
> 
> 我前两天的PR尝试修复了在macOS上的问题，您可以尝试用nightly build的whl再跑一次。

收到，感谢，我下午试一下

**Comment by sduqlsc** [comment]
@scyyh11 使用如下版本可行：

```bash
python -m pip install --pre paddlepaddle -i https://www.paddlepaddle.org.cn/packages/nightly/cpu/

pip list|grep padd
paddleocr                3.2.0
paddlepaddle             3.3.0.dev20251012
paddlex                  3.2.1

```

测试代码：

```python
ocr = PaddleOCR(
            lang="ch",
            device='cpu',
            enable_mkldnn=False,
            cpu_threads=8,
            use_doc_orientation_classify=False,
            use_doc_unwarping=False,
            use_textline_orientation=True
        )

# pdf 路径
result = ocr.predict(image_path)

print(result)
```

另外，我发现如下设置也会影响解析，ARM64下直接报错 `Segmentation fault`

```python
# os.environ['OMP_NUM_THREADS'] = '1'

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1760337452 (unix time) try "date -d @1760337452" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 182117 (TID 0xfffd09c8f120) from PID 0 ***]

^CSegmentation fault (core dumped)

```

**Comment by scyyh11** [comment]
> [@scyyh11](https://github.com/scyyh11) 使用如下版本可行：
> 
> python -m pip install --pre paddlepaddle -i https://www.paddlepaddle.org.cn/packages/nightly/cpu/
> 
> pip list|grep padd
> paddleocr                3.2.0
> paddlepaddle             3.3.0.dev20251012
> paddlex                  3.2.1
> 测试代码：
> 
> ocr = PaddleOCR(
>             lang="ch",
>             device='cpu',
>             enable_mkldnn=False,
>             cpu_threads=8,
>             use_doc_orientation_classify=False,
>             use_doc_unwarping=False,
>             use_textline_orientation=True
>         )
> 
> # pdf 路径
> result = ocr.predict(image_path)
> 
> print(result)
> 另外，我发现如下设置也会影响解析，ARM64下直接报错 `Segmentation fault`
> 
> # os.environ['OMP_NUM_THREADS'] = '1'
> 
> --------------------------------------
> C++ Traceback (most recent call last):
> --------------------------------------
> No stack trace in paddle, may be caused by external reasons.
> 
> ----------------------
> Error Message Summary:
> ----------------------
> FatalError: `Segmentation fault` is detected by the operating system.
>   [TimeInfo: *** Aborted at 1760337452 (unix time) try "date -d @1760337452" if you are using GNU date ***]
>   [SignalInfo: *** SIGSEGV (@0x0) received by PID 182117 (TID 0xfffd09c8f120) from PID 0 ***]
> 
> ^CSegmentation fault (core dumped)

好的感谢，但我不是paddle内部人员，不一定能保证完成这个issue的修复。

**Comment by scyyh11** [comment]
@sduqlsc 您好，我在本地尝试相同设置时并未复现该问题。从您提供的 error message 中 “No stack trace in paddle, may be caused by external reasons.” 可以看出，崩溃可能源于本地环境，而非 Paddle 内部。

**Comment by TingquanGao** [comment]
感谢 [scyyh11](https://github.com/scyyh11) 解答并修复此问题！

由于未得到回复，该 issue 将关闭，如仍有疑问请 reopen 或 new issue 提问。

感谢对 PaddleOCR 的关注~
